/**
 * Model3D Component
 *
 * Procedurally generated primitive meshes (cube, sphere, plane, etc.).
 * Unlike GLTFModel/FBXModel, this does NOT reference an asset - geometry is generated by the renderer.
 *
 * IMPORTANT: This component MUST be used with Transform3D component.
 */

import { component } from "@voidscript/core";

export type PrimitiveType = "cube" | "sphere" | "plane" | "cylinder" | "capsule";

export interface Model3DData {
  /**
   * Type of primitive to generate
   */
  type: PrimitiveType;

  /**
   * Size of the primitive (interpretation depends on type)
   * - cube: side length
   * - sphere: radius
   * - plane: side length
   * - cylinder: radius
   * - capsule: radius
   */
  size: number;

  /**
   * Whether to cast shadows
   * @default true
   */
  castShadow: boolean;

  /**
   * Whether to receive shadows
   * @default true
   */
  receiveShadow: boolean;
}

export const Model3D = component<Model3DData>("Model3D", {
  type: {
    serializable: true,
  },
  size: {
    serializable: true,
  },
  castShadow: {
    serializable: true,
  },
  receiveShadow: {
    serializable: true,
  },
});
